// Shot map for footage/tour.mp4.
//
// tour.mp4 is assembled from footage/source.mp4 by build-footage.sh as the
// segments in TIMELINE, in order. Holds are motion-interpolated to OUT_FPS;
// moves are the raw whip pans. TIMELINE must stay identical to the table in
// build-footage.sh. All start/end values are SOURCE seconds (26.06s clip, 16 fps).

// tracks.js is regenerated often; load it with a cache-busting query so a
// browser never keeps a stale copy of it.
const { TRACKS } = await import(`./tracks.js?v=${Date.now()}`);

export const SOURCE_FPS = 16;
export const OUT_FPS = 48;

export const TIMELINE = [
  { name: 'deskHold',     start: 1.0,   end: 3.0,  dir: 'fwd', kind: 'hold' },
  { name: 'deskHoldRev',  start: 1.0,   end: 3.0,  dir: 'rev', kind: 'hold' },
  { name: 'deskToDrums',  start: 7.0,   end: 9.25, dir: 'fwd', kind: 'move' },
  { name: 'drumsToDesk',  start: 7.0,   end: 9.25, dir: 'rev', kind: 'move' },
  { name: 'drumsHold',    start: 10.0,  end: 14.0, dir: 'fwd', kind: 'hold' },
  { name: 'drumsHoldRev', start: 10.0,  end: 14.0, dir: 'rev', kind: 'hold' },
  { name: 'drumsToPrint', start: 16.75, end: 18.5, dir: 'fwd', kind: 'move' },
  { name: 'printToDrums', start: 16.75, end: 18.5, dir: 'rev', kind: 'move' },
  { name: 'printHold',    start: 20.0,  end: 23.0, dir: 'fwd', kind: 'hold' },
  { name: 'printHoldRev', start: 20.0,  end: 23.0, dir: 'rev', kind: 'hold' },
];

// Playback settings. These are not exposed to visitors.
export const PLAYBACK = {
  holdSpeed: 0.5,     // holds play at half speed so the drift is gentle (footage is 48 fps, so still smooth)
  moveSpeed: 1.0,     // whip pans
  chainSpeed: 1.8,    // extra multiplier when two moves are chained (desk <-> printer)
  pingPong: true,     // reverse at the end of a hold instead of dissolving back to its start
  dissolveMs: 600,
};

// Letterbox: solid black bars top and bottom. The header (logo, tabs, pause)
// lives in the top bar, the footer (caption, hint, numbered buttons) in the
// bottom one; the drum keycaps stay on the footage.
// `fit` picks how the footage meets the bars:
//   'overlay'  the footage is laid out exactly as full-bleed (fills the viewport,
//              focus crop) and the bars sit on top of it. Full width, nothing
//              resized; the bars hide the outer 48/40 px of the frame.
//   'contain'  the whole 16:9 frame sits between the bars; `top`/`bottom` are
//              minimums, spare height goes into the bars, and a window wider than
//              16:9 shows the frame centred with black sides.
// Set `enabled: false` to drop the bars and go back to the gradient header/footer.
export const LETTERBOX = {
  enabled: true,
  fit: 'overlay',
  top: 48,      // px (logo 30px, tabs 34px, pause button 38px fit inside)
  bottom: 40,   // px (caption + 28px numbered buttons fit inside)
};

// Sections. `hold` names the forward segment and its reversed twin.
// `focus` is the point (% of the frame) the viewport crop centres on when the
// screen is narrower than 16:9 (phones). The crop pans between sections.
// Hotspot tracks come from tracks.js (generated by track-hotspots.py); an inline
// `track` on a hotspot overrides the generated one.
// `content` is what the modal shows when the hotspot is clicked:
//   { type: 'module', module }  an ES module whose default export renders into
//                               the modal body: (container, ctx) -> cleanup()
//                               (content/about.js is the ported portfolio About page)
//   { type: 'html', html }      inline markup
//   omitted                     a placeholder
export const SECTIONS = [
  {
    id: 'desk',
    label: 'Desk',
    caption: 'Work hard.',
    focus: { x: 57, y: 38 },
    hold: { fwd: 'deskHold', rev: 'deskHoldRev' },
    hotspots: [
      { id: 'monitor', label: 'About me', title: 'About', content: { type: 'module', module: './content/about.js' } },
      { id: 'keyboard', label: 'Portfolio', title: 'Portfolio', content: { type: 'module', module: './content/works.js' } },
    ],
  },
  {
    id: 'drums',
    label: 'Drums',
    caption: 'Play hard.',
    focus: { x: 56, y: 48 },
    hold: { fwd: 'drumsHold', rev: 'drumsHoldRev' },
    hotspots: [
      { id: 'hihat',    label: 'Hi-hat',    title: 'Hi-hat' },
      { id: 'crash',    label: 'Crash',     title: 'Crash' },
      { id: 'tom',      label: 'Tom',       title: 'Rack tom' },
      { id: 'ride',     label: 'Ride',      title: 'Ride' },
      { id: 'snare',    label: 'Snare',     title: 'Art', content: { type: 'module', module: './content/art.js' } },
      { id: 'kick',     label: 'Kick',      title: 'Kick' },
      { id: 'floortom', label: 'Floor tom', title: 'Floor tom' },
      { id: 'crash2',   label: 'Stop',      title: 'Stop drums' },   // far-right cymbal: play-mode off switch (shown only while playing)
    ],
  },
  {
    id: 'printer',
    label: 'Printer',
    caption: 'Say hello.',
    focus: { x: 55, y: 45 },
    hold: { fwd: 'printHold', rev: 'printHoldRev' },
    hotspots: [
      { id: 'monitor', label: 'Contact', title: 'Contact', content: { type: 'module', module: './content/contact.js' } },
      { id: 'printer', label: '3D printer', title: 'Misc', content: { type: 'html', html: '<div class="dp-soon"><h3>Coming soon</h3><p>Something is printing. Check back later.</p></div>' } },
    ],
  },
];

// Camera moves: ordered lists of segment names. `chain: true` marks a chained
// move that plays at moveSpeed * chainSpeed.
export const MOVES = {
  'desk>drums':    [ 'deskToDrums' ],
  'drums>printer': [ 'drumsToPrint' ],
  'drums>desk':    [ 'drumsToDesk' ],
  'printer>drums': [ 'printToDrums' ],
  'desk>printer':  { chain: true, segments: [ 'deskToDrums', 'drumsToPrint' ] },
  'printer>desk':  { chain: true, segments: [ 'printToDrums', 'drumsToDesk' ] },
};

// ---- derived ----

const SEG = (() => {
  let t = 0;
  const map = {};
  for (const s of TIMELINE) {
    const length = s.end - s.start;
    map[s.name] = { ...s, offset: t, length };
    t += length;
  }
  return map;
})();

export const TOUR_DURATION = TIMELINE.reduce((sum, s) => sum + (s.end - s.start), 0);

/** A segment as a playable clip in tour.mp4 time. */
export function clip(name) {
  const s = SEG[name];
  if (!s) throw new Error(`Unknown segment ${name}`);
  return { name, start: s.offset, end: s.offset + s.length, forward: s.dir === 'fwd', kind: s.kind };
}

/** tour.mp4 time -> source time, so hotspot tracks work inside reversed segments. */
export function toSourceTime(tourTime) {
  for (const s of Object.values(SEG)) {
    if (tourTime >= s.offset && tourTime < s.offset + s.length) {
      const u = tourTime - s.offset;
      return s.dir === 'fwd' ? s.start + u : s.end - u;
    }
  }
  const last = TIMELINE[TIMELINE.length - 1];
  return last.dir === 'fwd' ? last.end : last.start;
}

/** Keyframes for a hotspot: inline track, else the generated one. */
export function trackFor(section, hotspot) {
  return hotspot.track || TRACKS[section.id]?.[hotspot.id] || [];
}

export function sectionIndex(id) {
  return SECTIONS.findIndex((s) => s.id === id);
}
